ASSUME DS:DATA,CS:CODE
DATA SEGMENT
    DB 'XXXXXXUNIVERSITY'
    DB '................'
DATA ENDS

CODE SEGMENT
START:
    MOV AX,DATA
    MOV DS,AX
    MOV CX,0008H
    MOV SI,0
    MOV DI,0010H
S:  MOV AX,[SI]
    MOV [DI],AX
    ADD SI,2
    ADD DI,2
    LOOP S
    MOV AH,4CH
    INT 21H
CODE ENDS
END START